name = "Prose"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-prose/blob/master/LICENSE.md"
description = "A minimalist Hugo theme inspired by the academic theme, distill.pub, and tufte.css."
homepage = "https://prose.yihui.org"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.55.0"

[author]
  name = "Yihui Xie"
  homepage = "https://yihui.org"
